name: Changeset

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "chore: version pump"
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
