name: Lint Commits & Code

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
  commitlint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Install commitlint
        run: |
          yarn add conventional-changelog-conventionalcommits
          yarn add commitlint@latest
      - name: Validate latest commit
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  eslint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: yarn add next eslint eslint-config-next
      - name: Run Eslint
        run: yarn lint
