name: Test Tauri Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "public/**"
      - ".husky/**"
      - ".gitignore"
      - ".github/**"
      - ".vscode/**"
      - ".changeset/**"
      - "apps/web/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "public/**"
      - ".husky/**"
      - ".gitignore"
      - ".github/**"
      - ".vscode/**"
      - ".changeset/**"
      - "apps/web/**"
  workflow_dispatch:

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          sparse-checkout: |
            apps/core

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "apps/core/src-tauri -> target"

      - uses: pnpm/action-setup@v2
        with:
          run_install: |
            - recursive: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: install tauri cli
        run: pnpm add -w @tauri-apps/cli

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--debug"
          includeRelease: false
          includeDebug: true
